### ISSUE TITLE
Are we using Flat Doc?

### ISSUE THREAD

**Issue by paked** [hackclub/hackclub#557] opened 2015-12-12 01:49 UTC
Currently we have the flat doc license in our LICENSE file.

https://github.com/hackclub/hackclub/blob/master/LICENSE#L22-L25

I can't see any uses of it anywhere in master though

**Comment by zachlatta** [comment] 2015-12-12 02:26
https://github.com/hackclub/hackclub/blob/master/workshops/maze/readme.html and https://github.com/hackclub/hackclub/blob/master/workshops/maze/css/style.css are the two uses of it, though I'm against using flatdoc. I think we should keep everything on GitHub to lower the barrier as much as possible to contributions.

**Comment by paked** [comment] 2015-12-13 21:52
@zachlatta should we delete these files? They don't seem to be doing much?

**Comment by paked** [comment] 2015-12-16 03:30
@jonleung I'd really like to delete these files, they seem to be serving 0 purpose. Is this possible?

**Comment by MaxWofford** [comment] 2015-12-19 04:25
'bug' doesn't seem like an appropriate tag for this.

**Comment by MaxWofford** [comment] 2015-12-19 04:25
Labeling as 'discussion' because the issue is being discussed.

**Comment by MaxWofford** [comment] 2015-12-19 04:26
In-case we do want to go through with this though, I've created https://github.com/hackclub/hackclub/pull/603

**Comment by MaxWofford** [comment] 2016-01-10 11:39
Closing this because #603 was merged

**Closed by MaxWofford** 2016-01-10 11:39 UTC
Labels: discussion

**Comment by zachlatta** [comment] 2016-01-11 00:44
Thanks for bringing this up @paked. I'm terribly sorry for not properly
responding to you earlier :-(. I'm glad we have a resolution now.

On Sun, Jan 10, 2016 at 3:39 AM, Max Wofford <notifications@github.com>
wrote:

> Closing this because #603 <https://github.com/hackclub/hackclub/pull/603>
> was merged
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackclub/hackclub/issues/557#issuecomment-170337518>.
>



-- 
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta
